---
packages:
- name: acceptance-tests
  version: !binary |-
    NzNiNzU5OWE1ZDExMjcwNjQzZWY3MmRkMmRjOTQ4YjhhNDJiZjFlZg==
  fingerprint: !binary |-
    NzNiNzU5OWE1ZDExMjcwNjQzZWY3MmRkMmRjOTQ4YjhhNDJiZjFlZg==
  sha1: !binary |-
    ZGNmYzY4NjM5OTY2MGM2ODkyNjIyOTEwYTAyM2U2NDE3MzZkMmRhYQ==
  dependencies:
  - golang1.4
- name: bash-4.3
  version: !binary |-
    N2MxNzkyZmU2MTA2MzA4MjE5YWZjOWNkZjUzN2Q1OGUzZjU2ZDY0OQ==
  fingerprint: !binary |-
    N2MxNzkyZmU2MTA2MzA4MjE5YWZjOWNkZjUzN2Q1OGUzZjU2ZDY0OQ==
  sha1: !binary |-
    NzlkODE2ODRmNWI3NWRkMTU1Y2U4MjdmMmFlYjIyMzFiODNkMzMzMA==
  dependencies: []
- name: consul-template
  version: !binary |-
    ZGJmOTJmYjA1NmY0ZmNkZjU5YTZmYzc2OWM0ODFmMjA0MGY1ODU5ZA==
  fingerprint: !binary |-
    ZGJmOTJmYjA1NmY0ZmNkZjU5YTZmYzc2OWM0ODFmMjA0MGY1ODU5ZA==
  sha1: !binary |-
    NjQ4NTEyODVmZmRjZGZlMzg5MzhjMjZlZGJjMWM1ODQzNzI3Mzg0Zg==
  dependencies: []
- name: consul-ui
  version: !binary |-
    MTY0YzhmOTY2NWM5ZTJmYmVkMmQ3YzFkYjVhNzUwOTg0YmFkY2Y5OA==
  fingerprint: !binary |-
    MTY0YzhmOTY2NWM5ZTJmYmVkMmQ3YzFkYjVhNzUwOTg0YmFkY2Y5OA==
  sha1: !binary |-
    YmIwZGQzMjIxMGNiYjk3ZjJkYWFlOWNhMzY1MzU4NThmYTE3YjU2OA==
  dependencies: []
- name: consul
  version: !binary |-
    M2IxZmFmZDJmY2UyNzIyY2Q2ZjcwMzY2NmNlYjAyN2FkMjFkMDJjYw==
  fingerprint: !binary |-
    M2IxZmFmZDJmY2UyNzIyY2Q2ZjcwMzY2NmNlYjAyN2FkMjFkMDJjYw==
  sha1: !binary |-
    ZTAyNThkZTJkMmM0YmY2MmYzNDA2ZjkzNDNiOGI0NDRkYzIyZjMwMA==
  dependencies: []
- name: golang1.4
  version: !binary |-
    MjU4Y2E3OWRjMjU3ZWMyN2ZhMjFmNjM2NmQyZDE4NDhmZjZmZGU3Zg==
  fingerprint: !binary |-
    MjU4Y2E3OWRjMjU3ZWMyN2ZhMjFmNjM2NmQyZDE4NDhmZjZmZGU3Zg==
  sha1: !binary |-
    MWM4NjNkNGM4N2U3MjYwYzdkMmQ1ZjExODkyNDVmZTYwNTkyYzQyNQ==
  dependencies: []
- name: haproxy
  version: !binary |-
    YzBkZjM1MmZkMjMwMDk3NzZlMjUzOTUwZDAwOWY3MmQ5ZGE0MjlkNw==
  fingerprint: !binary |-
    YzBkZjM1MmZkMjMwMDk3NzZlMjUzOTUwZDAwOWY3MmQ5ZGE0MjlkNw==
  sha1: !binary |-
    ZjUxNjJhYTMyNjNiYzJkNmYyNmUzOTI0NGVkM2MxNzIyZjk1YjM1Mw==
  dependencies:
  - pcre
  - socat
  - zlib
- name: libevent
  version: !binary |-
    MzkxZWVhZGJiNGU5MDY2NzQ4ZWQ0YmRiZWY4NjIzMGJjOTRlODFmMg==
  fingerprint: !binary |-
    MzkxZWVhZGJiNGU5MDY2NzQ4ZWQ0YmRiZWY4NjIzMGJjOTRlODFmMg==
  sha1: !binary |-
    NzBlMmMwZjE5ZjE4YzhmNzFkYmQ4OWJlYWVhODgxYTk5NmRiMDRhZg==
  dependencies: []
- name: pcre
  version: !binary |-
    MjE3ZTQ2MTIyNGM3Mjk4YjkzMWYzZWFlMzY0ODlmMGZlMDBkYzYyMg==
  fingerprint: !binary |-
    MjE3ZTQ2MTIyNGM3Mjk4YjkzMWYzZWFlMzY0ODlmMGZlMDBkYzYyMg==
  sha1: !binary |-
    YzYzYmY1MTc2NTE3ZDMxZDBlMGQxNjIzYmNiYmZlY2MwNWM4ZmQ5Yw==
  dependencies: []
- name: pgbdr
  version: !binary |-
    ODI1Y2NiOTJlYzJlODFhMmQyYTUyNjNjYzk4NTQ0YTNiOGM4YTU3Ng==
  fingerprint: !binary |-
    ODI1Y2NiOTJlYzJlODFhMmQyYTUyNjNjYzk4NTQ0YTNiOGM4YTU3Ng==
  sha1: !binary |-
    NTRiZTNmOTE4MDM4MjgxZmM4YmY3ODI3MTM5MzliN2ViOWY0YjRkNg==
  dependencies:
  - bash-4.3
- name: pgbouncer
  version: !binary |-
    MTFkZDcxZTI3MjlhNjcxNTYyOTM4NWM5NmE3ZDE5NGFiOGJkNDcyZg==
  fingerprint: !binary |-
    MTFkZDcxZTI3MjlhNjcxNTYyOTM4NWM5NmE3ZDE5NGFiOGJkNDcyZg==
  sha1: !binary |-
    ZTAxNDhhNTI3YzU4NmJkYThhMDE1OWJmODUzZjg4YzU2OWE3YThjYw==
  dependencies:
  - libevent
- name: rdpgd
  version: !binary |-
    NTEzZWU3OTc2M2Q2M2FjMWQ3OWNmODMzZTVlYTgzOTQ0YmFiZGQ2NA==
  fingerprint: !binary |-
    NTEzZWU3OTc2M2Q2M2FjMWQ3OWNmODMzZTVlYTgzOTQ0YmFiZGQ2NA==
  sha1: !binary |-
    MDNhYmI4MWIzMzAwNzk1OWM0NWM3ODNmZDA5YzRmYzEyMWNjNWJlMg==
  dependencies:
  - golang1.4
- name: socat
  version: !binary |-
    YmExNzFmOWNmM2QzMzgwNWJlNWI4YWI4NmYxYzlkMDllYzMzZGU4OQ==
  fingerprint: !binary |-
    YmExNzFmOWNmM2QzMzgwNWJlNWI4YWI4NmYxYzlkMDllYzMzZGU4OQ==
  sha1: !binary |-
    MTgzZjY0M2E4YmNmZjZlNmZiYTBiZWYzMTJkMDA4NDhkYTJjN2VmMA==
  dependencies: []
- name: zlib
  version: !binary |-
    Zjk4ZDczNmM4NTJhODFjODZhNzdhNmY2ODdiOGMzZGNmYTNiOTIwNg==
  fingerprint: !binary |-
    Zjk4ZDczNmM4NTJhODFjODZhNzdhNmY2ODdiOGMzZGNmYTNiOTIwNg==
  sha1: !binary |-
    YjM0NjkyNGIwNDA3NGVhOTM0OWVhYTBlNjA4N2E5Y2MzNGIwNzI4ZQ==
  dependencies: []
jobs:
- name: acceptance-tests
  version: !binary |-
    MzBkYWU0MTVhOGUwZGJmNWY5MmNjN2IwNWViZTZlNWNjZGEyYjRkOA==
  fingerprint: !binary |-
    MzBkYWU0MTVhOGUwZGJmNWY5MmNjN2IwNWViZTZlNWNjZGEyYjRkOA==
  sha1: !binary |-
    MTkyZjliODcwYzY1YTk1MjNiNDMyNTgxNzhkZmU0MTNhNGJjODVlMg==
- name: consul-template
  version: !binary |-
    NDg0OWVmZTEyMTk4MTZhNTBhMmZjNDE0ZTBjYWM0NzYwNDc5ODE4Yw==
  fingerprint: !binary |-
    NDg0OWVmZTEyMTk4MTZhNTBhMmZjNDE0ZTBjYWM0NzYwNDc5ODE4Yw==
  sha1: !binary |-
    MTg4MDhmOWNjOGQwODY1MDE0YjdiOWFhNGU5OWRhNGQ5ODQ4NTljNg==
- name: consul
  version: !binary |-
    NzdmYjYxNWI1YWMyYmRiYjllZDBjYzdmNzNiODdiYjU0MGRjZDEwYg==
  fingerprint: !binary |-
    NzdmYjYxNWI1YWMyYmRiYjllZDBjYzdmNzNiODdiYjU0MGRjZDEwYg==
  sha1: !binary |-
    MDUyNzQ4ZWI1YjM5MjAyNzM0YjJiMTI3YWFmMzJiZThhZDIwYWNmMw==
- name: haproxy
  version: !binary |-
    MmNhNDhlNWU0ZDk5ZWM4NGQ4MjQzNzgwYWZhMDlkZTcyNmQwMzczYw==
  fingerprint: !binary |-
    MmNhNDhlNWU0ZDk5ZWM4NGQ4MjQzNzgwYWZhMDlkZTcyNmQwMzczYw==
  sha1: !binary |-
    NjZiMDIyYzk4MzM1M2U3MTNmYzFlYTk3OGMzMjc4MjYzMTliNmFiNw==
- name: pgbdr
  version: !binary |-
    NjUzMDRhNTg5ZjIyM2ExYmVhN2E2YmQ2MWUyNDVhNTA5YWJiMDY3OQ==
  fingerprint: !binary |-
    NjUzMDRhNTg5ZjIyM2ExYmVhN2E2YmQ2MWUyNDVhNTA5YWJiMDY3OQ==
  sha1: !binary |-
    MzMzNTc4NzRhYWU0ZTAxYjcyNmFlNDcyMzcwZjE4NjVlNTU1Yzc0Ng==
- name: pgbouncer
  version: !binary |-
    ZWQ1MjMxNWVlNGExZmUwYjdhYWIzMDViMDJlMjVhMzI2YmNlMmE3Ng==
  fingerprint: !binary |-
    ZWQ1MjMxNWVlNGExZmUwYjdhYWIzMDViMDJlMjVhMzI2YmNlMmE3Ng==
  sha1: !binary |-
    NDNkMzAxNmExOTM3ZTk0MWU4YjYwYjQ4NDlkNjUxZmZiNWFhMDIxZg==
- name: rdpgd-manager
  version: !binary |-
    MTA0ZGM4YmY2NDE3YWY5NzI5MjQ5OTA0NjY5YWUyOTVjNjRkZGM5Mg==
  fingerprint: !binary |-
    MTA0ZGM4YmY2NDE3YWY5NzI5MjQ5OTA0NjY5YWUyOTVjNjRkZGM5Mg==
  sha1: !binary |-
    YmIyMjRjNTE5MDQzZWI3OGQ2ZDUwYmQ3MTU2MmE2NDNlZjliNmM4ZQ==
- name: rdpgd-service
  version: !binary |-
    ZDc5NDAwZjc1NzIyZGU1MTJhMzMyYTJiZDY5MDIxY2Y1NmU5NTdmOA==
  fingerprint: !binary |-
    ZDc5NDAwZjc1NzIyZGU1MTJhMzMyYTJiZDY5MDIxY2Y1NmU5NTdmOA==
  sha1: !binary |-
    OWNhNmE4NjRiYzgyNzk5MDA0ZGJjY2MzYjhhYjFmZmU1MTA3OGM3YQ==
license:
  version: !binary |-
    NjI2NmU2ZDcyNDYwZTBhYWNjZGEyNDQwMTQ1OTBiNGI2NDc0MzRlZg==
  fingerprint: !binary |-
    NjI2NmU2ZDcyNDYwZTBhYWNjZGEyNDQwMTQ1OTBiNGI2NDc0MzRlZg==
  sha1: !binary |-
    ZjUyNTNkNzhiZDZhMzhiNmJlNzEwYTMzYzIyNzNkNWNiZDFjZThjNA==
commit_hash: d4d0228d
uncommitted_changes: false
name: rdpg
version: 0.2.31
